server:
  port: 9999
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true

spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: 123456

  http:
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 15MB
      max-request-size: 150MB
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml